language: node_js
node_js:
- '5'
- '4.2'
- '0.12'
deploy:
  provider: npm
  email: simbo@simbo.de
  api_key: "${NPM_API_KEY}"
  on:
    tags: true
    repo: simbo/gulp-static-site-generator
after_script:
- npm run cover
- npm run codeclimate
sudo: false
env:
  global:
  - secure: WTO38mEfqQUb7YNin142SaHzr01vkxct4LQtg8cWSmF4c9Lh94gH6FJRTWY+1wNSQVtbmaMnn6rqnMTGahRDO+H0ZGblgQVWHQUKDRe783OUUQkmoCb3ICFrweJ4WKVkVFi5dBzNZYAzG/UHnVcz/VnnZ8uOAkyaLdfZa4tJOJ1JbPKEXA0A3jlle+DPEwFwziDz5HX921cTNExzudF3p2PML5TvvpksuKyaYplM6ADw3z2fPu+MRAHTrDp5yS9Rh6Olk9mH5+QHZ1bI0QGwKaFDOMVcfjoryU0Z3DkDnSoZ2Ej+XKtshMiw8hAxHX8xJvcxgAhE8Jfl0XEGNUU2gVfQnet6q2nRATVsxoM51oREEWZNeki4jX09cUqQG/aPidj9rrXZocGetJxaFpWvjG1DsFR+v/nDrtTDKXxafx5NypsakBoY9rt+oR+XHRTF0WZaFAlrvx9xuulkaAwiRNpgnmu9Axo7XpIvG99IomapYEFqz7xM5Z44JNYA+ESeVmX47rEig2kGrwXQ8Pgpo/ZrthPVgmr1MtQe2aMLvs+jgABf5A7Q57qyIBUiu60g/t4hhVX4plmh51Jly6OZpzGq9cCA1DVOaFglmFuLeLcB7UDM+/wGtJ9flZ/orw0/H/PH3jjPBk7YTijX5GkFeGRxTSF+Y9xzBXsvWTD9RSA=
  - secure: fB3FmJ7TDR+2tH/VWtWP690wLXpksuWoGJJABhgFFntM6jdaIjja/tEvi7c0rmFf3hQSE4golgqSqug7yfXjlVnMG+D+vP5K3H/cjHwpFrNKWaPXNAz4tCTH9en0lu68qsVAalPT5FgUeI5s+o5iFBK1DoDRvwaVp5pRQavqZ8eDmzbVuxqFI1zhiHqEO6hQxpI08iBqPfMwxbV1hz/MpM8tMlzPHQWN+2Xhnm+ZIK9h5vCxqMCDGwA+9GbTBOIA7fquJvT0rGLqaKv+1f1YSssjPy3WjnxnxFXC7SjSSF9TjZD4MQ4SkIbpFdTLiD53+TljJ1Z6DFCN9uHq5S18ByyGZ3mI8UD7zq7DFYDxmD3YVz+FEXBx0OvlkYwLkuCDISonfFWyqFqvzZUjYQ7QGaRv2voqABp0birsU9dHuJFsiR6PV6EJd5Hb9hltBpspHSgaxYDeyeH2IOHz9eTO868K9hoOcnkExSamKL1MzGB3ebeZesD7jY6BUZSF25NtW3dZouihcdkbVrjCP0zKy66ovh42IokTgjQjS1FgwK6c1dhXxhr1EaxFTBj3BSSpA3HmgJbLX3BfntEHg1cZw3pJ7EvQmlSgHVmmHxQTecKEu1WbRV+qE4HvPAYEeiuMs5NiMVpBlDF0UBZmdYYkeXFoJVgWwvEMlBBi8RzuPFo=
