language: node_js
node_js:
- '5'
- '4.2'
- '0.12'
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/f97030d9bd589dd13aa3
    on_success: always
    on_failure: always
    on_start: never
deploy:
  provider: npm
  email: simbo@simbo.de
  api_key: "${NPM_API_KEY}"
  on:
    tags: true
    repo: simbo/gulp-static-site-generator
after_script:
- npm run cover
- npm run codecov
- npm run codeclimate
sudo: false
env:
  global:
  - secure: WTO38mEfqQUb7YNin142SaHzr01vkxct4LQtg8cWSmF4c9Lh94gH6FJRTWY+1wNSQVtbmaMnn6rqnMTGahRDO+H0ZGblgQVWHQUKDRe783OUUQkmoCb3ICFrweJ4WKVkVFi5dBzNZYAzG/UHnVcz/VnnZ8uOAkyaLdfZa4tJOJ1JbPKEXA0A3jlle+DPEwFwziDz5HX921cTNExzudF3p2PML5TvvpksuKyaYplM6ADw3z2fPu+MRAHTrDp5yS9Rh6Olk9mH5+QHZ1bI0QGwKaFDOMVcfjoryU0Z3DkDnSoZ2Ej+XKtshMiw8hAxHX8xJvcxgAhE8Jfl0XEGNUU2gVfQnet6q2nRATVsxoM51oREEWZNeki4jX09cUqQG/aPidj9rrXZocGetJxaFpWvjG1DsFR+v/nDrtTDKXxafx5NypsakBoY9rt+oR+XHRTF0WZaFAlrvx9xuulkaAwiRNpgnmu9Axo7XpIvG99IomapYEFqz7xM5Z44JNYA+ESeVmX47rEig2kGrwXQ8Pgpo/ZrthPVgmr1MtQe2aMLvs+jgABf5A7Q57qyIBUiu60g/t4hhVX4plmh51Jly6OZpzGq9cCA1DVOaFglmFuLeLcB7UDM+/wGtJ9flZ/orw0/H/PH3jjPBk7YTijX5GkFeGRxTSF+Y9xzBXsvWTD9RSA=
  - secure: fB3FmJ7TDR+2tH/VWtWP690wLXpksuWoGJJABhgFFntM6jdaIjja/tEvi7c0rmFf3hQSE4golgqSqug7yfXjlVnMG+D+vP5K3H/cjHwpFrNKWaPXNAz4tCTH9en0lu68qsVAalPT5FgUeI5s+o5iFBK1DoDRvwaVp5pRQavqZ8eDmzbVuxqFI1zhiHqEO6hQxpI08iBqPfMwxbV1hz/MpM8tMlzPHQWN+2Xhnm+ZIK9h5vCxqMCDGwA+9GbTBOIA7fquJvT0rGLqaKv+1f1YSssjPy3WjnxnxFXC7SjSSF9TjZD4MQ4SkIbpFdTLiD53+TljJ1Z6DFCN9uHq5S18ByyGZ3mI8UD7zq7DFYDxmD3YVz+FEXBx0OvlkYwLkuCDISonfFWyqFqvzZUjYQ7QGaRv2voqABp0birsU9dHuJFsiR6PV6EJd5Hb9hltBpspHSgaxYDeyeH2IOHz9eTO868K9hoOcnkExSamKL1MzGB3ebeZesD7jY6BUZSF25NtW3dZouihcdkbVrjCP0zKy66ovh42IokTgjQjS1FgwK6c1dhXxhr1EaxFTBj3BSSpA3HmgJbLX3BfntEHg1cZw3pJ7EvQmlSgHVmmHxQTecKEu1WbRV+qE4HvPAYEeiuMs5NiMVpBlDF0UBZmdYYkeXFoJVgWwvEMlBBi8RzuPFo=
  - secure: jg8K5usqO/WtfpIdh2ZxM1PZIfvHnWy3AYePfQOx6Dm1ArDWaGylEKtzy831J4SjKeXp7EW9JgZgUXJLDDX0OnrqMPCXUd+nwEVoQ562jm2/Vdv4CKJpZT3uCzKoTd7ANO1dRcJzse0GPrWV+voQY+b+P/VwuuK42io0suEVs6SWWr0sU+mN+hdvB6dkDs1mNdY80n0aEijXv6Nv/Lpzgmebw/vlnhLJAMfvZv5x3et4cLgh2dnF8FDBtZnryVvdoiPOP8e4/D5pNmk8Py+go2X8fx2ZJA8SNG8RPewkv6A+eEW4uotPCQy96OiZ5tHMY6eMQVoxcmnVeGBU8kRxzHkJUXNP8jcAGsH6l69ATKpX0QsH37H9bz+c3sBe98jLxTHSJyIpJ561LbYHhbxws5TQ4HkcPJuLyDPqyI1a5ubfHZ2ZXUbIcCLWF+CcPN918OzZg3foYbKj5NzLqfur9QQrm2QY/mx9Nu98j1a+QPa+YuKfTWPY1Bgpup9P1L4VxwJGXnCJu1ybHm+EsmD/Q6nHRcCozQh68errU1QBMYn64J/mSagLO1qEyhBBxsYs5N/ZcmLzGdfXl+taOOOpp38sXB7PeLdlBZMHz/q7lsl8zbsvFrv7rqZxR45MMqQGw86ZMPEsOCDNXFOg49qdzlh7dvN+vvarvlkgjB5hDKw=
